CREATE OR REPLACE 
    VIEW VW_LAST_12_HOUR 
AS 
SELECT 
    ID_MACHINE_REGISTER MACHINE_REGISTER_ID,
    TRUNC(EXEC_TIME, 'HH') MINU,
    SUM(CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
    SUM(FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
    SUM(OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
    SUM(RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
    SUM(TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
    SUM(NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
    COUNT(1) TOTAL_REGISTER
FROM MACHINE_INFO
WHERE MACHINE_INFO.EXEC_TIME > SYSDATE - 1/24*12
GROUP BY 
    ID_MACHINE_REGISTER,      
    TRUNC(EXEC_TIME, 'hh')
ORDER BY MINU;    




----
CREATE OR REPLACE 
    VIEW VW_LAST_HOUR 
AS 
SELECT 
      ID_MACHINE_REGISTER MACHINE_REGISTER_ID,
    TRUNC(EXEC_TIME, 'MI') MINU,
    SUM(CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
    SUM(FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
    SUM(OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
    SUM(RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
    SUM(TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
    SUM(NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
    COUNT(1) TOTAL_REGISTER
FROM MACHINE_INFO
WHERE MACHINE_INFO.EXEC_TIME > SYSDATE - 1/24
GROUP BY 
    ID_MACHINE_REGISTER,      
    TRUNC(EXEC_TIME, 'MI')
ORDER BY MINU;    

-------------------------

CREATE OR REPLACE 
    VIEW VW_LAST_15_MIN 
AS 
SELECT 
    ID_MACHINE_REGISTER MACHINE_REGISTER_ID,
    TRUNC(EXEC_TIME, 'MI') MINU,
    SUM(CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
    SUM(FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
    SUM(OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
    SUM(RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
    SUM(TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
    SUM(NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
    COUNT(1) TOTAL_REGISTER
FROM MACHINE_INFO
WHERE MACHINE_INFO.EXEC_TIME > SYSDATE - 1/24/60*15
GROUP BY 
    ID_MACHINE_REGISTER,      
    TRUNC(EXEC_TIME, 'MI')
ORDER BY MINU;    

-------------------------

CREATE OR REPLACE 
    VIEW VW_LAST_30_MIN 
AS 
SELECT 
    ID_MACHINE_REGISTER MACHINE_REGISTER_ID,
    TRUNC(EXEC_TIME, 'MI') MINU,
    SUM(CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
    SUM(FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
    SUM(OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
    SUM(RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
    SUM(TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
    SUM(NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
    COUNT(1) TOTAL_REGISTER
FROM MACHINE_INFO
WHERE MACHINE_INFO.EXEC_TIME > SYSDATE - 1/24/60*30
GROUP BY 
    ID_MACHINE_REGISTER,      
    TRUNC(EXEC_TIME, 'MI')
ORDER BY MINU;    

-------------------------

CREATE OR REPLACE 
    VIEW VW_LAST_6_HOUR 
AS 
SELECT 
    ID_MACHINE_REGISTER MACHINE_REGISTER_ID,
    TRUNC(EXEC_TIME, 'HH') MINU,
    SUM(CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
    SUM(FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
    SUM(OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
    SUM(RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
    SUM(TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
    SUM(NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
    COUNT(1) TOTAL_REGISTER
FROM MACHINE_INFO
WHERE MACHINE_INFO.EXEC_TIME > SYSDATE - 1/24*6
GROUP BY 
    ID_MACHINE_REGISTER,      
    TRUNC(EXEC_TIME, 'HH')
ORDER BY MINU;   

-------------------------

CREATE OR REPLACE 
    VIEW VW_LAST_DAY 
AS 
SELECT 
    ID_MACHINE_REGISTER MACHINE_REGISTER_ID,
    TRUNC(EXEC_TIME, 'HH') MINU,
    SUM(CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
    SUM(FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
    SUM(OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
    SUM(RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
    SUM(TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
    SUM(NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
    COUNT(1) TOTAL_REGISTER
FROM MACHINE_INFO
WHERE MACHINE_INFO.EXEC_TIME > SYSDATE - 1
GROUP BY 
    ID_MACHINE_REGISTER,      
    TRUNC(EXEC_TIME, 'HH')
ORDER BY MINU;