CREATE OR REPLACE 
    VIEW VW_GROUP_Last_15_MIN
AS
SELECT  G.ID_MACHINE_MONITORING_GROUP GROUP_ID,
        SUM(i.CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
        TRUNC(i.EXEC_TIME, 'MI') MINU,        
        SUM(i.FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
        SUM(i.OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
        SUM(i.RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
        SUM(i.TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
        SUM(i.NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
        COUNT(1) TOTAL_REGISTER
    FROM MACHINE_MONITORING_GROUP G
    INNER JOIN MACHINE_MONITORING_REGISTER R
    ON G.ID_MACHINE_MONITORING_GROUP = R.FK_MONITORING
    INNER JOIN MACHINE_INFO i 
    ON R.FK_REGISTER = i.ID_MACHINE_REGISTER 
    and i.EXEC_TIME > SYSDATE - 1/24/60*15
    GROUP BY 
    G.ID_MACHINE_MONITORING_GROUP,      
    TRUNC(i.EXEC_TIME, 'MI')
ORDER BY MINU;
--------------

CREATE OR REPLACE 
    VIEW VW_GROUP_Last_30_MIN
AS
SELECT  G.ID_MACHINE_MONITORING_GROUP GROUP_ID,
        SUM(i.CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
        TRUNC(i.EXEC_TIME, 'MI') MINU,        
        SUM(i.FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
        SUM(i.OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
        SUM(i.RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
        SUM(i.TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
        SUM(i.NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
        COUNT(1) TOTAL_REGISTER
    FROM MACHINE_MONITORING_GROUP G
    INNER JOIN MACHINE_MONITORING_REGISTER R
    ON G.ID_MACHINE_MONITORING_GROUP = R.FK_MONITORING
    INNER JOIN MACHINE_INFO i 
    ON R.FK_REGISTER = i.ID_MACHINE_REGISTER 
    and i.EXEC_TIME > SYSDATE - 1/24/60*30
    GROUP BY 
    G.ID_MACHINE_MONITORING_GROUP,      
    TRUNC(i.EXEC_TIME, 'MI')
ORDER BY MINU;
------------------------
CREATE OR REPLACE 
    VIEW VW_GROUP_Last_1_HOUR
AS
SELECT  G.ID_MACHINE_MONITORING_GROUP GROUP_ID,
        SUM(i.CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
        TRUNC(i.EXEC_TIME, 'MI') MINU,        
        SUM(i.FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
        SUM(i.OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
        SUM(i.RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
        SUM(i.TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
        SUM(i.NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
        COUNT(1) TOTAL_REGISTER
    FROM MACHINE_MONITORING_GROUP G
    INNER JOIN MACHINE_MONITORING_REGISTER R
    ON G.ID_MACHINE_MONITORING_GROUP = R.FK_MONITORING
    INNER JOIN MACHINE_INFO i 
    ON R.FK_REGISTER = i.ID_MACHINE_REGISTER 
    and i.EXEC_TIME > SYSDATE - 1/24
    GROUP BY 
    G.ID_MACHINE_MONITORING_GROUP,      
    TRUNC(i.EXEC_TIME, 'MI')
ORDER BY MINU;
------------------------
CREATE OR REPLACE 
    VIEW VW_GROUP_Last_6_HOUR
AS
SELECT  G.ID_MACHINE_MONITORING_GROUP GROUP_ID,
        SUM(i.CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
        TRUNC(i.EXEC_TIME, 'HH') MINU,        
        SUM(i.FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
        SUM(i.OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
        SUM(i.RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
        SUM(i.TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
        SUM(i.NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
        COUNT(1) TOTAL_REGISTER
    FROM MACHINE_MONITORING_GROUP G
    INNER JOIN MACHINE_MONITORING_REGISTER R
    ON G.ID_MACHINE_MONITORING_GROUP = R.FK_MONITORING
    INNER JOIN MACHINE_INFO i 
    ON R.FK_REGISTER = i.ID_MACHINE_REGISTER 
    and i.EXEC_TIME > SYSDATE - 1/24*6
    GROUP BY 
    G.ID_MACHINE_MONITORING_GROUP,      
    TRUNC(i.EXEC_TIME, 'HH')
ORDER BY MINU;
------------------------
CREATE OR REPLACE 
    VIEW VW_GROUP_Last_12_HOUR
AS
SELECT  G.ID_MACHINE_MONITORING_GROUP GROUP_ID,
        SUM(i.CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
        TRUNC(i.EXEC_TIME, 'HH') MINU,        
        SUM(i.FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
        SUM(i.OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
        SUM(i.RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
        SUM(i.TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
        SUM(i.NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
        COUNT(1) TOTAL_REGISTER
    FROM MACHINE_MONITORING_GROUP G
    INNER JOIN MACHINE_MONITORING_REGISTER R
    ON G.ID_MACHINE_MONITORING_GROUP = R.FK_MONITORING
    INNER JOIN MACHINE_INFO i 
    ON R.FK_REGISTER = i.ID_MACHINE_REGISTER 
    and i.EXEC_TIME > SYSDATE - 1/24*12
    GROUP BY 
    G.ID_MACHINE_MONITORING_GROUP,      
    TRUNC(i.EXEC_TIME, 'HH')
ORDER BY MINU;
------------------------
CREATE OR REPLACE 
    VIEW VW_GROUP_Last_1_DAY
AS
SELECT  G.ID_MACHINE_MONITORING_GROUP GROUP_ID,
        SUM(i.CPU_USAGE_PERCENT) / COUNT(1) CPU_AVG,
        TRUNC(i.EXEC_TIME, 'HH') MINU,        
        SUM(i.FREE_DISK) /COUNT(1) FREE_DISK_AVG,  
        SUM(i.OCCUPIED_DISK) /COUNT(1) OCCUPIED_DISK_AVG,   
        SUM(i.RAM_USAGE_PERCENT) / COUNT(1) RAM_AVG,
        SUM(i.TOTAL_MEMORY) /COUNT (1) TOTAL_MEMORY_AVG,
        SUM(i.NUMBER_OF_CORES) / COUNT(1)NUMBER_OF_CORES_AVG,
        COUNT(1) TOTAL_REGISTER
    FROM MACHINE_MONITORING_GROUP G
    INNER JOIN MACHINE_MONITORING_REGISTER R
    ON G.ID_MACHINE_MONITORING_GROUP = R.FK_MONITORING
    INNER JOIN MACHINE_INFO i 
    ON R.FK_REGISTER = i.ID_MACHINE_REGISTER 
    and i.EXEC_TIME > SYSDATE - 1
    GROUP BY 
    G.ID_MACHINE_MONITORING_GROUP,      
    TRUNC(i.EXEC_TIME, 'HH')
ORDER BY MINU;




